### ISSUE TITLE
Bug: wekelijkse lijst werkt niet meert.

### ISSUE THREAD

**Issue by stefjoosten** [Ordina-Group/Stichting-NUTwente#739]
# Wat er gebeurde
Een coördinator probeerde een wekelijkse lijst van gastgezinnen af te drukken.
Daartoe zette zij de volgende stappen:
1. navigeer naar `https://nutwente.azurewebsites.net/` en log in
2. klik op archief > download en maak een download van de Gastgezinnen per gemeente.
Dit laatste gaat fout en geeft de volgende foutmelding.

![image](https://github.com/Ordina-Group/Stichting-NUTwente/assets/275768/809b1835-3504-4b27-a41e-a0e6d5571405)

De hele gang van zaken vind je in het onderstaande videofragment.

https://github.com/Ordina-Group/Stichting-NUTwente/assets/275768/9cf3aa2f-586e-45d2-9ddd-bd57dfd3b2ea

# Wat ik verwachtte
Tot voor kort kreeg ik keurig netjes een overzicht van de gastgezinnen per gemeente.

**Comment by stefjoosten** [comment]
# Analyse
De log van de foutmelding laat het volgende zien:
```
System.Net.Http.HttpRequestException: Response status code does not indicate success: 410 (Gone).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.Json.HttpClientJsonExtensions.GetFromJsonAsyncCore[T](Task`1 taskResponse, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Ordina.StichtingNuTwente.Business.Services.DocumentService.GemeenteFromPostcodeAsync(String postCode) in /home/runner/work/Stichting-NUTwente/Stichting-NUTwente/Ordina.StichtingNuTwente/Ordina.StichtingNuTwente.Business/Services/DocumentService.cs:line 132
```
Dit verwijst naar `public async Task<string> GemeenteFromPostcodeAsync(string postCode)` in Documentservice.cs.
Daarin is een [URL](https://geodata.nationaalgeoregister.nl/locatieserver/v3/free) vermeld om een postcode op te zoeken. 
Dat is meteen verdacht, omdat het wijzigen van een URL kan verklaren waarom de code het "plotseling" niet meer doet.

En inderdaad. Een korte speurtocht liet zien dat `https://geodata.nationaalgeoregister.nl/locatieserver/v3/free` niet langer werkt. Vanaf 2 augustus 2023 is dit gemigreerd naar `https://api.pdok.nl/bzk/locatieserver/search/v3_1/free`. Een en ander  staat [beschreven](https://www.pdok.nl/-/migratie-pdok-locatieserver-naar-het-nieuwe-3g-platform-afgerond) op internet.

# Diagnose
De URL `https://geodata.nationaalgeoregister.nl/locatieserver/v3/free` werkt niet langer. Ik heb deze in de code vervangen door `https://api.pdok.nl/bzk/locatieserver/search/v3_1/free`. Nu moet de applicatie alleen nog getest worden en in productie genomen.
